INHERIT: ../base.yml
site_url: http://docs/dev

extra:
  portal_name: Dev

extra_css:
  - !ENV [OTHERS_STYLESHEETS_PORTAL_SELECTION, "../stylesheets/portal_selection.css"]
  - !ENV [OTHERS_STYLESHEETS_COLORS, "../stylesheets/colors.css"]

nav:
  - "index.md"
  - Tasks:
      - "tasks/rm-custom-views.md"
  # - Runtimes:
  #     - "runtimes/sdk-runtimes.md"
