{
 "title": "Demo ETL",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Posizione delle spire",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \"codice spira\", tipologia, \"Nome via\", direzione, longitudine, latitudine FROM demo_etl.spire;",
     "queryTimeout": 60
    }
   ]
  },
  {
   "title": "Veicoli per spira nel periodo di riferimento",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \"codice spira\", SUM(totale_giornaliero) AS veicoli FROM demo_etl.misurazioni_giornaliere\nGROUP BY \"codice spira\"\nORDER BY veicoli DESC;",
     "queryTimeout": 60,
     "timeCol": "data"
    }
   ]
  },
  {
   "title": "Veicoli registrati in totale per mese",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT data, SUM(totale_giornaliero) AS veicoli FROM demo_etl.misurazioni_giornaliere GROUP BY data;",
     "queryTimeout": 60,
     "timeCol": "data"
    }
   ]
  }
 ]
}