INHERIT: ../base.yml
site_url: http://docs/sdk

extra:
  portal_name: SDK

extra_javascript:
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js

extra_css:
  - stylesheets/cards.css
  - stylesheets/tables.css
  - !ENV [
      OTHERS_STYLESHEETS_PORTAL_SELECTION,
      "../stylesheets/portal_selection.css",
    ]
  - !ENV [OTHERS_STYLESHEETS_COLORS, "../stylesheets/colors.css"]

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: { alternate_style: true }
  - pymdownx.highlight:
      { anchor_linenums: true, line_spans: __span, pygments_lang_class: true }
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - md_in_html

plugins:
  - search: {}
  - redirects:
      redirect_maps:
        how-to/quickstart.md: tutorials/quickstart.md
        how-to/runtime-guide.md: explanations/choosing-a-runtime.md
        how-to/what-can-i-do.md: explanations/what-can-i-do.md
        reference/runtimes/container/how-to.md: explanations/runtimes/container-execution.md
        reference/runtimes/dbt/how-to.md: explanations/runtimes/dbt-execution.md
        reference/runtimes/flower/how-to.md: explanations/runtimes/flower-execution.md
        reference/runtimes/hera/how-to.md: explanations/runtimes/hera-execution.md
        reference/runtimes/modelserve/how-to.md: explanations/runtimes/modelserve-execution.md
        reference/runtimes/servicegraph/how-to.md: explanations/runtimes/servicegraph-execution.md
        reference/runtimes/python/python/how-to.md: explanations/runtimes/python-execution.md
        reference/runtimes/python/openinference/how-to.md: explanations/runtimes/openinference-execution.md
        reference/runtimes/python/guardrail/how-to.md: explanations/runtimes/guardrail-execution.md
        reference/configuration/paths/overview.md: reference/configuration/paths.md
        reference/configuration/paths/local.md: reference/configuration/paths.md#local-paths
        reference/configuration/paths/s3.md: reference/configuration/paths.md#s3-paths
        reference/configuration/paths/remote.md: reference/configuration/paths.md#remote-paths-https
        reference/configuration/paths/hf.md: reference/configuration/paths.md#hugging-face-paths
        reference/configuration/paths/sql.md: reference/configuration/paths.md#sql-paths
        reference/configuration/code_src/overview.md: reference/configuration/code-sources.md
        reference/configuration/code_src/local.md: reference/configuration/code-sources.md#local-file
        reference/configuration/code_src/http.md: reference/configuration/code-sources.md#https-file-or-zip
        reference/configuration/code_src/git.md: reference/configuration/code-sources.md#git-repository
        reference/configuration/code_src/s3.md: reference/configuration/code-sources.md#s3-zip-archive
        reference/configuration/credentials/overview.md: reference/configuration/credentials.md
        reference/configuration/credentials/dhcore.md: reference/configuration/credentials.md#dhcore-api
        reference/configuration/credentials/s3.md: reference/configuration/credentials.md#s3-storage
        reference/configuration/credentials/sql.md: reference/configuration/credentials.md#sql-databases
        reference/configuration/credentials/git.md: reference/configuration/credentials.md#git-repositories
        reference/configuration/credentials/helpers.md: reference/configuration/credentials.md#helpers-and-clients
        reference/configuration/credentials/store-clients.md: reference/configuration/credentials.md#store-clients
        reference/configuration/kubernetes/overview.md: reference/configuration/kubernetes.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_toc_entry: false
            show_labels: false

theme:
  features:
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.code.select

nav:
  - Index: index.md
  - Tutorials:
      - Getting Started: tutorials/index.md
      - First Python function: tutorials/quickstart.md
      - Data Processing & Transformation:
          - ETL Data Processing: tutorials/etl-data-processing.md
          - Database Transformation with DBT: tutorials/dbt-transformation.md
      - Machine Learning:
          - Scikit-Learn Model Training: tutorials/scikit-learn-model.md
          - MLflow Model Management: tutorials/mlflow-model.md
          - Custom ML Models with Darts: tutorials/custom-ml-model.md
      - AI & Large Language Models:
          - Large Language Models: tutorials/llm-model.md
  - How-to Guides:
      - Guides: how-to/index.md
      - Installation: how-to/installation.md
      - Kubernetes guide: how-to/kubernetes.md
  - Explanations:
      - Overview: explanations/index.md
      - What can I do?: explanations/what-can-i-do.md
      - Data and artifacts: explanations/data-and-artifacts.md
      - Choosing a runtime: explanations/choosing-a-runtime.md
      - Runtime execution models:
          - Python: explanations/runtimes/python-execution.md
          - OpenInference: explanations/runtimes/openinference-execution.md
          - Guardrail: explanations/runtimes/guardrail-execution.md
          - DBT: explanations/runtimes/dbt-execution.md
          - Container: explanations/runtimes/container-execution.md
          - Hera: explanations/runtimes/hera-execution.md
          - ModelServe: explanations/runtimes/modelserve-execution.md
          - Flower: explanations/runtimes/flower-execution.md
          - ServiceGraph: explanations/runtimes/servicegraph-execution.md
  - Reference:
      - Overview: reference/index.md
      - Entities:
          - Index: reference/objects/index.md
          - Projects:
              - Entity: reference/objects/project/entity.md
              - CRUD: reference/objects/project/crud.md
              - Methods: reference/objects/project/methods.md
              - Config: reference/objects/project/config.md
              - Setup: reference/objects/project/setup.md
          - Functions:
              - Entity: reference/objects/function/entity.md
              - CRUD: reference/objects/function/crud.md
              - Methods: reference/objects/function/methods.md
          - Workflows:
              - Entity: reference/objects/workflow/entity.md
              - CRUD: reference/objects/workflow/crud.md
              - Methods: reference/objects/workflow/methods.md
          - Tasks:
              - Entity: reference/objects/task/entity.md
              - CRUD: reference/objects/task/crud.md
              - Methods: reference/objects/task/methods.md
          - Triggers:
              - Entity: reference/objects/trigger/entity.md
              - CRUD: reference/objects/trigger/crud.md
              - Methods: reference/objects/trigger/methods.md
              - Kind:
                  - Scheduler: reference/objects/trigger/kind/scheduler.md
                  - Lifecycle: reference/objects/trigger/kind/lifecycle.md
          - Runs:
              - Entity: reference/objects/run/entity.md
              - CRUD: reference/objects/run/crud.md
              - Methods: reference/objects/run/methods.md
          - Secrets:
              - Entity: reference/objects/secret/entity.md
              - CRUD: reference/objects/secret/crud.md
              - Methods: reference/objects/secret/methods.md
              - Kind:
                  - Secret: reference/objects/secret/kind/secret.md
          - Artifacts:
              - Entity: reference/objects/artifact/entity.md
              - CRUD: reference/objects/artifact/crud.md
              - Methods: reference/objects/artifact/methods.md
              - Kind:
                  - Artifact: reference/objects/artifact/kind/artifact.md
          - Dataitems:
              - Entity: reference/objects/dataitem/entity.md
              - CRUD: reference/objects/dataitem/crud.md
              - Methods: reference/objects/dataitem/methods.md
              - Kind:
                  - Dataitem: reference/objects/dataitem/kind/dataitem.md
                  - Table: reference/objects/dataitem/kind/table.md
                  - Croissant: reference/objects/dataitem/kind/croissant.md
          - Models:
              - Entity: reference/objects/model/entity.md
              - CRUD: reference/objects/model/crud.md
              - Methods: reference/objects/model/methods.md
              - Kind:
                  - Model: reference/objects/model/kind/model.md
                  - MLflow: reference/objects/model/kind/mlflow.md
                  - Scikit-learn: reference/objects/model/kind/sklearn.md
                  - Hugging Face: reference/objects/model/kind/huggingface.md
                  - TVM IR: reference/objects/model/kind/tvm-ir.md
                  - TVM SO: reference/objects/model/kind/tvm-so.md
          - Container images:
              - Entity: reference/objects/containerimage/entity.md
              - CRUD: reference/objects/containerimage/crud.md
              - Methods: reference/objects/containerimage/methods.md
              - Kind:
                  - Container image: reference/objects/containerimage/kind/container-image.md
      - Runtimes:
          - Index: reference/runtimes/index.md
          - Python:
              - Overview: reference/runtimes/python/python/overview.md
              - Handler definition: reference/runtimes/python/python/define-function.md
              - Generic handler: reference/runtimes/python/define-function.md
              - Actions:
                  - python job: reference/runtimes/python/python/actions/python-job.md
                  - python serve: reference/runtimes/python/python/actions/python-serve.md
                  - python build: reference/runtimes/python/python/actions/python-build.md
              - Examples: reference/runtimes/python/python/examples.md
          - OpenInference (Python):
              - Overview: reference/runtimes/python/openinference/overview.md
              - Handler definition: reference/runtimes/python/openinference/define-function.md
              - Actions:
                  - openinference serve: reference/runtimes/python/openinference/actions/openinference-serve.md
                  - openinference build: reference/runtimes/python/openinference/actions/openinference-build.md
              - Examples: reference/runtimes/python/openinference/examples.md
          - Guardrail (Python):
              - Overview: reference/runtimes/python/guardrail/overview.md
              - Handler definition: reference/runtimes/python/guardrail/define-function.md
              - Actions:
                  - guardrail serve: reference/runtimes/python/guardrail/actions/guardrail-serve.md
                  - guardrail build: reference/runtimes/python/guardrail/actions/guardrail-build.md
              - Examples: reference/runtimes/python/guardrail/examples.md
          - DBT:
              - Overview: reference/runtimes/dbt/overview.md
              - Actions:
                  - dbt transform: reference/runtimes/dbt/actions/dbt-transform.md
              - Examples: reference/runtimes/dbt/examples.md
          - Container:
              - Overview: reference/runtimes/container/overview.md
              - Actions:
                  - container job: reference/runtimes/container/actions/container-job.md
                  - container serve: reference/runtimes/container/actions/container-serve.md
                  - container build: reference/runtimes/container/actions/container-build.md
              - Examples: reference/runtimes/container/examples.md
          - Hera:
              - Overview: reference/runtimes/hera/overview.md
              - Pipeline definition: reference/runtimes/hera/define-pipeline.md
              - Actions:
                  - hera build: reference/runtimes/hera/actions/hera-build.md
                  - hera pipeline: reference/runtimes/hera/actions/hera-pipeline.md
              - Examples: reference/runtimes/hera/examples.md
          - Modelserve:
              - Overview: reference/runtimes/modelserve/overview.md
              - Actions:
                  - sklearnserve serve: reference/runtimes/modelserve/actions/sklearnserve-serve.md
                  - mlflowserve build: reference/runtimes/modelserve/actions/mlflowserve-build.md
                  - mlflowserve serve: reference/runtimes/modelserve/actions/mlflowserve-serve.md
                  - huggingfaceserve serve: reference/runtimes/modelserve/actions/huggingfaceserve-serve.md
                  - kubeai-text serve: reference/runtimes/modelserve/actions/kubeai-text-serve.md
                  - kubeai-speech serve: reference/runtimes/modelserve/actions/kubeai-speech-serve.md
                  - vllmserve-text serve: reference/runtimes/modelserve/actions/vllmserve-text-serve.md
                  - vllmserve-speech serve: reference/runtimes/modelserve/actions/vllmserve-speech-serve.md
                  - vllmserve-pooling serve: reference/runtimes/modelserve/actions/vllmserve-pooling-serve.md
              - Examples: reference/runtimes/modelserve/examples.md
          - Flower:
              - Overview: reference/runtimes/flower/overview.md
              - Actions:
                  - flower-app train: reference/runtimes/flower/actions/flower-app-train.md
                  - flower-client build: reference/runtimes/flower/actions/flower-client-build.md
                  - flower-client deploy: reference/runtimes/flower/actions/flower-client-deploy.md
                  - flower-server build: reference/runtimes/flower/actions/flower-server-build.md
                  - flower-server deploy: reference/runtimes/flower/actions/flower-server-deploy.md
              - Examples: reference/runtimes/flower/examples.md
          - ServiceGraph:
              - Overview: reference/runtimes/servicegraph/overview.md
              - Actions:
                  - servicegraph serve: reference/runtimes/servicegraph/actions/servicegraph-serve.md
              - Examples: reference/runtimes/servicegraph/examples.md
      - Configuration:
          - Paths: reference/configuration/paths.md
          - Code source: reference/configuration/code-sources.md
          - Credentials: reference/configuration/credentials.md
          - Kubernetes resources: reference/configuration/kubernetes.md
