INHERIT: ../base.yml
site_url: http://docs/user

extra:
  portal_name: User

extra_css:
  - !ENV [USER_STYLESHEETS_PORTAL_SELECTION, "stylesheets/portal_selection.css"]
  - !ENV [USER_STYLESHEETS_COLORS, "stylesheets/colors.css"]

nav:
  - "index.md"
  - "architecture.md"
  - "quickstart.md"
  - "installation.md"
  #- "core.md"
  - Concepts and Tasks:
      - "tasks/projects.md"
      - "tasks/functions.md"
      - "tasks/models.md"
      - "tasks/kubernetes-resources.md"
      - "tasks/workflows.md"
      - "tasks/data.md"
      - "tasks/files.md"
      - "tasks/services.md"
      - "tasks/triggers.md"
      - "tasks/workspaces.md"
      - "tasks/metrics.md"
      - "tasks/code-source.md"
      - "tasks/secrets.md"
      - "tasks/pat.md"
    #   - "tasks/git.md"
  - Components:
      - "components/dashboard.md"
      - "components/dh_console.md"
      - "components/cli.md"
      - "components/resourcemanager.md"
      #   - "components/kubeflow.md"
      - "components/kubeai.md"
      - Interactive Workspaces:
          - "components/code-toolbox.md"
          - Community Workspaces:
              - "components/dremio.md"
              - "components/sqlpad.md"
              - "components/grafana.md"
  - Runtimes reference:
      - Overview: "runtimes/overview.md"
      - Python: "runtimes/python.md"
      - Container: "runtimes/container.md"
      - Hera Pipelines: "runtimes/hera.md"
      - "Model Serving: LLMs": "runtimes/llmserve.md"
      - "Model Serving: MLflow": "runtimes/mlflowserve.md"
      - "Model Serving: Speech to Text": "runtimes/asrserve.md"
      - "Model Serving: Scikit-learn": "runtimes/sklearnserve.md"
      - "Federated Learning": "runtimes/fl.md"
      - DBT: "runtimes/dbt.md"

  - SDK Reference:
      - "sdk/intro.md"

  - CLI Reference:
      - "cli/commands.md"
