INHERIT: ../base.yml
site_url: http://docs/user

extra:
  portal_name: User

extra_css:
  - !ENV [USER_STYLESHEETS_PORTAL_SELECTION, "stylesheets/portal_selection.css"]
  - !ENV [USER_STYLESHEETS_COLORS, "stylesheets/colors.css"]

nav:
  - "index.md"
  - "architecture.md"
  - "quickstart.md"
  - "installation.md"
  #- "core.md"
  - "entities.md"
  - Tasks:
    - Common Tasks:
        - "tasks/projects.md"
        - "tasks/functions.md"
        - "tasks/services.md"
        - "tasks/workflows.md"
        - "tasks/triggers.md"
        - "tasks/workspaces.md"
        - "tasks/kubernetes-resources.md"
        - "tasks/code-source.md"
        - "tasks/secrets.md"
        - "tasks/pat.md"
        #   - "tasks/git.md"
    - Data-related Tasks:
        - "data-tasks/data.md"
        - "data-tasks/files.md"
    - ML-related Tasks:
        - "ml-tasks/models.md"
        - "ml-tasks/metrics.md"
  - Components:
      - "components/dashboard.md"
      - "components/dh_console.md"
      - "components/cli.md"
      - "components/resourcemanager.md"
      #   - "components/kubeflow.md"
      - "components/kubeai.md"
      - Interactive Workspaces:
          - "components/code-toolbox.md"
          - Community Workspaces:
              - "components/dremio.md"
              - "components/sqlpad.md"
              - "components/grafana.md"
  - Runtimes reference:
      - Overview: "runtimes/overview.md"
      - Python: "runtimes/python.md"
      - Container: "runtimes/container.md"
      - Hera Pipelines: "runtimes/hera.md"
      - "Model Serving: LLMs": "runtimes/llmserve.md"
      - "Model Serving: MLflow": "runtimes/mlflowserve.md"
      - "Model Serving: Speech to Text": "runtimes/asrserve.md"
      - "Model Serving: Scikit-learn": "runtimes/sklearnserve.md"
      - Open Inference: "runtimes/oi.md"
      - Guardrail: "runtimes/guardrail.md"
      - "Federated Learning": "runtimes/fl.md"
      - DBT: "runtimes/dbt.md"

  - Extensions reference:
      - "extensions/overview.md"
      - "extensions/envoygw.md"

  - SDK Reference:
      - "sdk/intro.md"

  - CLI Reference:
      - "cli/commands.md"

  - Examples and Tutorials: "./tutorials/"