name: update-docs
run-name: Update docs
on:
  create:
    branches-ignore:
      - gh-pages
  push:
    branches-ignore:
      - main
      - gh-pages
    paths-ignore:
      - tutorials/docs/**/metadata.yaml
      - generate_tutorials_metadata.py
      - .github/workflows/generate-tutorials-metadata.yaml
concurrency:
  group: update-docs
  cancel-in-progress: false
permissions:
  contents: write
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install mkdocs-material
      - run: pip install mkdocs-redirects
      - run: |
          git fetch --prune --unshallow --tags origin "+refs/heads/*:refs/remotes/origin/*"
          this_branch=${{ github.ref_name }}
          echo "Triggered by event '${{ github.event_name }}' on branch '${this_branch}'"
          export VERSIONS=$(echo `git branch -r --format='%(refname:short)'`|python versions_string.py)
          echo "Versions are: ${VERSIONS}"
          git checkout main
          set -a
          source config.env
          echo "Stable version is: ${STABLE_VERSION}"
          export STABLE_DOCS="https://scc-digitalhub.github.io/docs/${STABLE_VERSION}"
          echo "Stable docs are available at: ${STABLE_DOCS}"
          echo "Number of versions to display: ${N_DISPLAY_VERSIONS}"
          export USER_STYLESHEETS_PORTAL_SELECTION='../stylesheets/portal_selection.css'
          export USER_STYLESHEETS_COLORS='../stylesheets/colors.css'
          export OTHERS_STYLESHEETS_PORTAL_SELECTION='../../stylesheets/portal_selection.css'
          export OTHERS_STYLESHEETS_COLORS='../../stylesheets/colors.css'
          for v in ${VERSIONS//,/ }
          do
            if [ "${{ github.event_name }}" == "create" ] || [ "$v" == "$this_branch" ]; then
              echo "Deploying docs for: $v"
              export DOCS_VERSION="v:$v"
              git checkout $v
              cd user && mkdocs build && cd ..
              cd admin && mkdocs build && cd ..
              cd tutorials && mkdocs build && cd ..
              cd sdk
              pip install -r requirements.txt || echo "Failed to install SDK requirements"
              mkdocs build || echo "Failed to build SDK documentation"
              cd ..
              python merge_search_indices.py
              mkdir -p ./site
              [ ! -d user/site ] || mv user/site site/$v
              [ ! -d admin/site ] || mv admin/site site/$v/admin
              [ ! -d tutorials/site ] || mv tutorials/site site/$v/tutorials
              [ ! -d sdk/site ] || mv sdk/site site/$v/sdk
            fi
          done
          git checkout gh-pages
          cp -r site/* .
          rm -r site
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git add --all
          git commit -m "Docs auto-generated by '${{ github.event_name }}' on branch '${{ github.ref_name }}'" --allow-empty
          git push